
package ru.stepanenko.tm.endpoint;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-05-13T22:20:29.879+03:00
 * Generated source version: 3.2.7
 */

@WebFault(name = "InputDataValidateException", targetNamespace = "http://endpoint.tm.stepanenko.ru/")
public class InputDataValidateException_Exception extends Exception {

    private ru.stepanenko.tm.endpoint.InputDataValidateException inputDataValidateException;

    public InputDataValidateException_Exception() {
        super();
    }

    public InputDataValidateException_Exception(String message) {
        super(message);
    }

    public InputDataValidateException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public InputDataValidateException_Exception(String message, ru.stepanenko.tm.endpoint.InputDataValidateException inputDataValidateException) {
        super(message);
        this.inputDataValidateException = inputDataValidateException;
    }

    public InputDataValidateException_Exception(String message, ru.stepanenko.tm.endpoint.InputDataValidateException inputDataValidateException, java.lang.Throwable cause) {
        super(message, cause);
        this.inputDataValidateException = inputDataValidateException;
    }

    public ru.stepanenko.tm.endpoint.InputDataValidateException getFaultInfo() {
        return this.inputDataValidateException;
    }
}
