package ru.stepanenko.tm.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-05-31T13:35:10.112+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://endpoint.tm.stepanenko.ru/", name = "ServerEndpoint")
@XmlSeeAlso({ObjectFactory.class})
public interface ServerEndpoint {

    @WebMethod
    @Action(input = "http://endpoint.tm.stepanenko.ru/ServerEndpoint/getInfoPortRequest", output = "http://endpoint.tm.stepanenko.ru/ServerEndpoint/getInfoPortResponse")
    @RequestWrapper(localName = "getInfoPort", targetNamespace = "http://endpoint.tm.stepanenko.ru/", className = "ru.stepanenko.tm.endpoint.GetInfoPort")
    @ResponseWrapper(localName = "getInfoPortResponse", targetNamespace = "http://endpoint.tm.stepanenko.ru/", className = "ru.stepanenko.tm.endpoint.GetInfoPortResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getInfoPort();

    @WebMethod
    @Action(input = "http://endpoint.tm.stepanenko.ru/ServerEndpoint/getInfoHostRequest", output = "http://endpoint.tm.stepanenko.ru/ServerEndpoint/getInfoHostResponse")
    @RequestWrapper(localName = "getInfoHost", targetNamespace = "http://endpoint.tm.stepanenko.ru/", className = "ru.stepanenko.tm.endpoint.GetInfoHost")
    @ResponseWrapper(localName = "getInfoHostResponse", targetNamespace = "http://endpoint.tm.stepanenko.ru/", className = "ru.stepanenko.tm.endpoint.GetInfoHostResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getInfoHost();
}
